### ISSUE TITLE
[Album list] Better loading UX

### ISSUE THREAD

**Issue by MatyasKriz** [lyarenei/JellyMusic#81]
This might apply to other lists with images, but it would be nicer to show a ProgressView when loading album art.

**Comment by lyarenei** [comment]
I think there was some issue with the image library which then made me to remove the ProgressView, but I'll take a look.

**Comment by lyarenei** [comment]
Incorrectly tagged fixing commit, should be [b41f79b](https://github.com/lyarenei/Medusic/commit/b41f79bae72377815c5c72b468d79c880e96eb78)
