### ISSUE TITLE
[Album detail] Disabled shuffle

### ISSUE THREAD

**Issue by MatyasKriz** [lyarenei/JellyMusic#82]
As a user I have no clue why the shuffle button is disabled and how to enable it (is it a premium feature?).

![image](https://github.com/lyarenei/Medusic/assets/6033733/7b7aa21a-a06b-401d-8b72-f701aaac85e6)

Perhaps it would be better to keep the button active and show a Drop with information about why shuffle is not available.

**Comment by lyarenei** [comment]
> As a user I have no clue why the shuffle button is disabled and how to enable it (is it a premium feature?).

No, it's simply not implemented at this moment. 😄 

> Perhaps it would be better to keep the button active and show a Drop with information about why shuffle is not available.

Yeah, I agree. I'll try to remember to leave these active as I go through the code. In this specific case, I plan to revisit the album detail implementation anyway (mainly to remove hacks for ios 14 from back in the day), so I'll address it there.
