### ISSUE TITLE
[Improvement] Remove volume control in current song detail screen

### ISSUE THREAD

**Issue by MatyasKriz** [lyarenei/JellyMusic#84]
IMO it would make more sense to exclude the volume control as it's simply connected to the system volume anyway which can be controlled by buttons/keys.

**Comment by lyarenei** [comment]
This could be said about all apps on ios, tbh. But then even apple chooses to show it, so I think there is a reason (probably something to do with accessibility). Personally I don't mind it there, it's not like it takes some precious space.

I'll make it configurable.

**Comment by MatyasKriz** [comment]
It might help if the volume slider was as slick as Apple's, but at the moment it's a basic component and it looks a bit off there.

**Comment by lyarenei** [comment]
I found out in #89 there's a way to hide the knob, so now (and with the speaker icons) it looks much better. 

If there is a way to scale it on drag like the playback progress slider, then that would be awesome, but I have no idea how to do that in uikit.

**Comment by lyarenei** [comment]
I have decided to not allow hiding the volume bar after all. Now with the speaker icons added and knob gone, the volume bar looks much more presentable, especially after changes in #93:

Before:
<img src="https://github.com/lyarenei/Medusic/assets/26324629/75b0f8f7-3ac7-4cb7-9926-1017badeb050" height=500 />

After:
<img src="https://github.com/lyarenei/Medusic/assets/26324629/6f2aa4c1-6016-4a8d-a935-6041dafa63c5" height=500 />

And not to mention it looks kind of weird without the volume bar at all.

Let me know what you think.

**Comment by MatyasKriz** [comment]
Yeah, it looks way better now. The spacing around the playback controls still feels a bit too large to me though, might be because of the monotonous background.

Actually it might be because in AM the album art casts shadow and the text below is positioned lower.

**Comment by lyarenei** [comment]
I think at this point it's just a catch 22. You will either have an empty space or obnoxiously big elements, especially on bigger screens. So, I think empty space is just the lesser evil and I went with that - at least for the time being. Unless of course there are more tricks to make the UI look nice regardless of the (reasonable range of) screen sizes.
