### ISSUE TITLE
[Album detail] Selecting a song glitches out the NowPlaying component

### ISSUE THREAD

**Issue by MatyasKriz** [lyarenei/JellyMusic#87]
It gets back on track after a while, but it looks weird.

**Comment by lyarenei** [comment]
I do not observe any glitches. Please provide steps to reproduce, thanks.

**Comment by MatyasKriz** [comment]
The steps are:
- open the app
- select any album
- click on a specific song

I can't however reproduce it at this time, so it might be a race condition. Basically the animation of the now playing component gets stuck midway, usually before any button is visible.

**Comment by lyarenei** [comment]
I think I remember seeing something like that back on ios14, but not now. 
Ideally, I'd like to use a library or something as the implementation is pretty lacking.

**Comment by MatyasKriz** [comment]
I'll try to take a look today if I can make it more resilient.

**Comment by MatyasKriz** [comment]
I couldn't find what caused it and can't reproduce it anymore. 😕
